### ISSUE TITLE
Latest build from README.md not on maven central

### ISSUE THREAD

**Issue by mattca** [dinstone/beanstalkc#5]
Hi,

Am just trying out beanstalkd and this client and noticed that in the README, version 2.3.0 is referenced:

```
<dependency>
  <groupId>com.dinstone</groupId>
  <artifactId>beanstalkc</artifactId>
  <version>2.3.0</version>
</dependency>
```

But 2.3.0 is not present on maven repository. 

Will proceed using 2.2.0 for now, thanks for the project!

**Comment by omxcodec** [comment]
+1
Beanstalk Client » 2.2.0
https://mvnrepository.com/artifact/com.dinstone/beanstalkc

**Comment by dinstone** [comment]
hi all，beanstalkc v2.3.0 has been submitted to the central repository。

**Comment by omxcodec** [comment]
done
